### ISSUE TITLE
Extension outdated on fresh install

### ISSUE THREAD

**Issue by ktaletsk** [vatlab/transient-display-data#2]
After installing `transient-display-data` from conda I get a message saying that extension is outdated: 

```
$ jupyter labextension list
JupyterLab v3.0.16
Other labextensions (built into JupyterLab)
   app dir: /opt/conda/share/jupyter/lab
        transient-display-data v0.4.0 enabled  X

   The following extension are outdated:
        transient-display-data
        
   Consider running "jupyter labextension update --all" to check for updates.
```

Running `jupyter labextension update --all` updates extension to 0.4.1, but triggers a jupyterlab rebuild. I am not sure, but I think it pulls the new version from `npm`. The source code indicates that it is 0.4.1 as well.

Is it possible to update the conda package to remove the warning?

**Comment by BoPeng** [comment]
Sorry, I did not realize that https://github.com/conda-forge/jupyterlab-transient-display-data-feedstock is still on version 0.4.0. I will have a look.

**Comment by BoPeng** [comment]
released version 0.4.1 on pypi, which should hopefully trigger a conda update.

**Comment by BoPeng** [comment]
transient-display-data 0.4.2 should be available on conda-forge now.

https://anaconda.org/conda-forge/jupyterlab-transient-display-data/files

**Comment by ktaletsk** [comment]
Thank you!
